[package]
name = "avail-play"
version = "0.1.0"
edition = "2021"

[dependencies]
avail-rust = { git = "https://github.com/availproject/avail", tag ="v2.2.5.1" }
serde = "1.0.216"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
dotenv = "0.15"
bincode = "1.3.3"
